language: node_js
nodejs:
  - 10

branches:
  only:
    - develop
    - /^release\/.*/
    - master

script:
  - npm run ci

notifications:
  email:
    recipients:
      - secure: "cVv/QBQsl3JhVlotI6aw71x0vk79g+IAeqADN0wxjnzUfwHiJa3GmCg7nNg4Ko6JK+TG5SKTWfuhu7rd6+Xf0XB8i4Uyp5mDxBy9tj016DAkmLUsFRn/has7I1FuIUq0q8K4ffJo3m0Wkto9YibYYceR7Ps2QYQMkJ6C+q0XekwVvIdTSWdC+H5/YlwCA2m0OgUGwl8HaM4/lrl2qq8QwlOn6Zs3mb1mMZPOBdrLr0rqsT14TU/BSDt/R9JxD3NjVkfKIaM/xsQFZyzLSGBt9Z17onJRmoTUhXtLvrdsz1YJYUgyQpZfkX4id9PGU8kthfxW9E5Pw2DAlKiAD0aWttRtYPVlaECmzYRcc9ViqFkCQNoWJ5HRGsYtkpSLT7e8ODSBHJMj0kvaT7jKH1q3P/CXNePeo138iV6xGyKId5CeJTDTh13dJLpVDkWzzc0vUMRxQrrQR5I215Ez8BjHG83QCM5mVeHmM8D8FhH5nUFPbSZHntOrXLIX6rHzaSfgCpfhga+hPAODVmqCU/G3yfrL5U6y2uheWtDpJUOhJGWXGERTGR62kQSrJqETu8G8dpIbU+W4HUIg0bmZ/Smy0A8Oplwgx0+UtyF7g3snfVhs5KCNCGGeWYaiV2Z7WEfFki9TRVJyOHU1hoW+5+djbKH1qJKl8dYNzSN8idOYgcc="
