language: node_js
nodejs:
  - 10

branches:
  only:
    - develop
    - /^release\/.*/
    - master

script:
  - npm run ci

notifications:
  email:
    recipients:
      - secure: rcvNa2MQIV1Hu0/PFQ9ZFrUggJC/i7/CKm2FvXhsgmZwEJXs4gasiOo6UDN6jp18zR/53IguHev0KlsudLrJ6g9/KvjQnEnf+eo9ZnvyAE4cAYoropjRVbtz02XzMDo8JFoTBvQkxwrASTUwSDXJVsFhjkvBraj18Oi5aJkijD5NUuc1F35OboG/S0hhsHFF2QZWmSvQQrgvRs9ADABbpyZZlUw4m224auK48/p4X17ETxthCzkpDJulaizYBO+UygjbCVtd1YP6q1QqgKvOrDcfNPG5hXps7oCz5Fcj1TqnYWXqfhos5vYJJcULJveA7DS3aQk0PG5RylZwtra3xibjJ6uRJjgBkXwgCSNJLVnqphFZFE5Xznt95x2KY/1kCTv5Bbl7vxj+JTeKXMQ+SILutQmad/8nGYMqrxkvIB6OHJwvnfwoEp7kDr5SC37IOdT8MnVz4RcQd0bPQoR1XIsETHWUxPFC1hFkVGHGcQxjs6FnMa5YOQUyPwwUQfe9VjdTpdrEEEzgEosJXOGNiof07bODHGK2yA41fa1p1SrmebemZysV8OWEr3HKqZB0Uq23gn41VHef4ICslPWeYS+dOrG72yXGPwvRX8D+r3tOrtYXefrS2flz0zf95yLcZ/u2i80YddzDk53/zMtY1vS5SwUPVLZe/3FNpAvuPtY=

deploy:
  provider: npm
  email:
    secure: XOVSeAAiZOwHzfNLdSBbWn2ylrLQ3R3RzSYxe2EX4UKMNq7Iw6Htk11rA7RYruoUT5qo5fZ5FPBdXxQXqOAX6o07VULLzsDvMV+VRVKBJtHAxCPaP2u25mXyVdJgPzmCz92kLOusqMXBmX+O75DXdtSIakw3ayzq6Qoj/Xk/bgu6Wdaymtcm1thOe3RTlJeFm0IQOU6N9LSaz8K4fOTzE1OuBVRD4hf7ANGn6HSLZ6iQU0C56m4jX1a5bNY9oA5SSYC0D1DmOgFACIjAHqbYKUh2L97ckw6CQTG5HH/3HproRxSBhwQLw1ncGPDgbnku7ER9AI9yr41EtBnb2uEnWloCMV8izkPqTHFsV+rXCwQWhJVLVg6OC/6Y09t021B2f8A95pOhZ2MAP/T+vjYoY8+STmpILxxVCyx4CR3JeNtq3yBs/uK2HsSf+BJZgPobmFNe1GUSlSGGF4gFT8m8a8zBuS8KW1KnGq9DPvd8NoA3lmpKuuuaTpEkgE6cCmb2x/9/ihgGkvBaBBmwMBt5x98LOsAxaJChbZmXI0lxcMBaEZpNeCIwf0uIhK+9Z67akKfCbml3S2WpTILhJvRJ+T0pVwsItuoTvOVO5h9kxIoi+fsGWHpkc/LQNLPI30/ZFucm2rXx9/ay13MlTCnOaFCC7Yfoeen7Vgd8dsv2gT8=
  api_key:
    secure: UsDGzOpkbjUoHl/l/ppJ8QOAGZZYCbphinVmX9nOqwCcsJ5kq5Jq1IGv/GD6vgyqIZWREzVS92wOClH2Q/9//v2fuwA4jHPILsyiI+8rOOJMnXpEpYMFL73inAblfyTHYRhK3nWQZtAEaT1x5h6EZ2eyuUyeA43WhDuVg4yWXZDVxQU8TFNkhjzcxOc8t3SpczROdzjuv0ahqXQTMqOSroaaWt7v1fJ4zYAU+haDOaQEUQFSV4YkzJ3/LbyuLOCe6kVyLoxr8q71GApnlg9l82fEvZEn+ixTyfXxO2/TzSoihQsyDEXkhGPjuDSkTxRANWrSlHVEJ68mEnfAYpkiudDB6PG5C/mXtJDOvdeAzZ31lXnBl/PTp9Glaaii3UZWddH7sstOvZFzyKhLWNrKNxuEygAVwizqlu2N9vfwZ7QHljdgHveJUqmRAZ2T47AO6Z7IhZINbtKpT832r2Npijkr9FAqgKzrWkvxadWqqViJkpdK+WbFwDv72gbrTZd19qeiMFmszwMl9lw9/rutIpaVQTZFec1tQbPRVIFRU6Za+7qWa20EJxFkc4B9UaOQ7kXgBZAmCNyYLxIAZBz8+9GxYFZa4diDZt4Ukw6K9hwZqJoLvfo1Ysz7n3UrkTSp2ZmU5Ffx4M79m1dmhWR5yHCJutPZAz52HkE1LwBgtfo=
  on:
    branch: master
  tag: alpha
