language: node_js
nodejs:
  - 10

branches:
  only:
    - develop
    - /^release\/.*/
    - master

script:
  - npm run ci

notifications:
  email:
    recipients:
      - secure: rcvNa2MQIV1Hu0/PFQ9ZFrUggJC/i7/CKm2FvXhsgmZwEJXs4gasiOo6UDN6jp18zR/53IguHev0KlsudLrJ6g9/KvjQnEnf+eo9ZnvyAE4cAYoropjRVbtz02XzMDo8JFoTBvQkxwrASTUwSDXJVsFhjkvBraj18Oi5aJkijD5NUuc1F35OboG/S0hhsHFF2QZWmSvQQrgvRs9ADABbpyZZlUw4m224auK48/p4X17ETxthCzkpDJulaizYBO+UygjbCVtd1YP6q1QqgKvOrDcfNPG5hXps7oCz5Fcj1TqnYWXqfhos5vYJJcULJveA7DS3aQk0PG5RylZwtra3xibjJ6uRJjgBkXwgCSNJLVnqphFZFE5Xznt95x2KY/1kCTv5Bbl7vxj+JTeKXMQ+SILutQmad/8nGYMqrxkvIB6OHJwvnfwoEp7kDr5SC37IOdT8MnVz4RcQd0bPQoR1XIsETHWUxPFC1hFkVGHGcQxjs6FnMa5YOQUyPwwUQfe9VjdTpdrEEEzgEosJXOGNiof07bODHGK2yA41fa1p1SrmebemZysV8OWEr3HKqZB0Uq23gn41VHef4ICslPWeYS+dOrG72yXGPwvRX8D+r3tOrtYXefrS2flz0zf95yLcZ/u2i80YddzDk53/zMtY1vS5SwUPVLZe/3FNpAvuPtY=

deploy:
  provider: npm
  api_key:
    secure: fgwm8zuUq/nF/YJZIPGfPSxWF4bt6Kt79u+AzBRtHutbW0/fazBOqqqZVhbJ8ahq6IOQ4IxZamSPVF97E4ceg576clFyONLu9HFZOadjqweFOdJksUTvWr7uIgaURI4dkVUmo/0MvfnwAPCuAk3Y0ccLvsSmxKu0BLPCOdT/vVLLL1hpWiJ2+o8n0xbXnT+li375NjcQUtq3Z14NzBxFwD9yE+T3m7ms4lqV/bYsVZAX2jUmNWHQ/a+xQY9NSTJXnedY7RiXcHOO8Lm4Ck77rZJMK3EMGoLvTjBbVh5hg9fHt8nMaNNZ8S2KYBhp6WSkesNxWnEmgq3GMsZ8N0kquSLVXmhulqeM7qkYnfJSHKqxlYAml0830S+vN+8PAEwxhDpWB/yqIUzjWpqq60biFG/LXlhDNVSz6ng0IvgZZXG3hbW73SS6ky7dRmSqw2Sq/BrncL7j312xSQ2EyBrERNchpGrMqtEWfRxzdy2FZIbBLY0zOm9vYM0fBta4UXI3yZdlYduG6YTRJnhlILaR+Wt/yJZN732Lw+tIvxXhErRF9gsq9d18Niuz8Du1cVX3Ltf+iHe54RXJpm/dAFyLC1rTREaiAyO0BnO6M1C8KEkg6H94sDexTktSIOyqrMRvA6e8FCrUjUhk4x9wrEP6mVGmN9KXO0QmOvEZ5bzeS94=
  on:
    branch: master
  tag: alpha
