# https://github.com/andreashuber69/async-css-plugin/blob/develop/README.md#----async-css-plugin
os: linux
dist: xenial
language: node_js
node_js:
- 16

branches:
  only:
  - develop
  - /^release\/.*/
  - master

before_script:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- ./cc-test-reporter before-build

script:
- npm run ci

after_script:
- ./cc-test-reporter format-coverage --input-type lcov ./coverage/lcov.info
- ./cc-test-reporter upload-coverage --id $CODECLIMATE_TEST_REPORTER_ID
- export CODECLIMATE_API_HOST=https://codebeat.co/webhooks/code_coverage
- export CODECLIMATE_REPO_TOKEN=8c3c1b09-c029-483a-a812-72e3d9583306
- npx codeclimate-test-reporter < coverage/lcov.info

deploy:
  provider: npm
  skip_cleanup: true
  email:
    secure: E0WqQq0SE2PzhNSy+LsmmIytZsaT6N2dlZETNsD67x+LKx9WtUqMofgpfPK0B1/9w4u15i5nL01shG6A2HbPOwDNQY8eD5lhr/pmlPleN4S1yJHvFBaRhvm1zXNpLLs/sewelPDByYeb9jrXyqmf0dVM6T8Bnerhtk0CXjMWK4kTYPltkJqz+NZeMkuwnkhxWR41mC96apuOSHnmQyCsaoTmJEls8tf2nUcAejQ1CFTjjDWLvbvoOIfh5gXhdxtOKdpdbosU2oDmnMqBRxpji9WzwqruPZBxRbPj402PBSmciWWgl8XT//vGTfUOWoVUmdxh8V+cfpnDOKlImliFREr6Tv3f1hacT+cr63DL5phkKWFPuOiYqV2ntHjdWNE9WElcwRMKuF0UvT8tUmsDTmyyt8KgrcQebT9XYxQc6LB+b0j4WLz2eY0168CVgDcFrnBDP3K3gcy0Z7peR6RnICUfBTb20NJOrak23hbAr8lgSGcUcD6TOoLW6VRBGLJkz85ms7DBLXZDUV9vkO442K6tNJ/xs8V1PmDWshWoW8E+YpZzzEH4D3gtdn1PWTkD7Qi1HJMrPSgg+QG8GYSQEGj2zasQDSjfID6OccRHRcSbNogVJS3/3Zr9SpD5nj5O0xdyrI0+tKjls6a/10Dn8DvKmiv5JfTLbhMy2aXtudg=
  api_token:
    secure: hur8lEf5vpmdd4oDlt057BaBJx33jJVqpiJutUwNORNxi2vZeWpcqaLwxLOlHkJFLzfNs7jqOUx53JKaj5gatTpC5USlMJCNPePks1RUlsX+9gf8HteMfdXRlxPpU2+RbiEBJbGGLJ2b0/qEIRRBO8jvPq51Y25jE7/LvPHG1RLqZWzAl2P6XHYFDI0+9pBOATcPPdAKaZKGYrsbhKqhVdDdcVIQJD5IEx7O6yHMxyeS3XbJa/PewaIaYbECl4BSNWfxTAEd19D+rXhXjzZj1TnyID0Rxkmpt8CWvbS1GZdoTYPLVYdJJg5P8fH/ZYLpGKbSuUaxVQDCZQsJHqwcRMopnMQ3Td1/AdGEIWOvaOn5AJ1bW8lgeE4gyGQIGSIdgWSLBiA2lUqNsXFafwpfNXIjiu4Yo6i01WFcQrtQtQ9Rjyh6ls/2DjevHg5Tx390Sr1Fj2zdALiA+N2bV1tT2ayT423tWoCfaVwRxzUxAYIry+WTcYi6KE069CBDhDEyZPEvims7qKZYI1H+3DIxhOTh11XMDDWUBcsEc/3HKTfyFrDalLVTBsRlf+gtABdek+h611BOoiQKdLOtHyPDbziT5nY2z6Fo+dY2fRR7F2rByN4TjtQgNddpAZQVHhGfDIIRVF1CZGT8KSdNIjEqQLlaXZx7knI9yY4lDF4oqg8=
  on:
    branch: master

notifications:
  email:
    recipients:
    - secure: rcvNa2MQIV1Hu0/PFQ9ZFrUggJC/i7/CKm2FvXhsgmZwEJXs4gasiOo6UDN6jp18zR/53IguHev0KlsudLrJ6g9/KvjQnEnf+eo9ZnvyAE4cAYoropjRVbtz02XzMDo8JFoTBvQkxwrASTUwSDXJVsFhjkvBraj18Oi5aJkijD5NUuc1F35OboG/S0hhsHFF2QZWmSvQQrgvRs9ADABbpyZZlUw4m224auK48/p4X17ETxthCzkpDJulaizYBO+UygjbCVtd1YP6q1QqgKvOrDcfNPG5hXps7oCz5Fcj1TqnYWXqfhos5vYJJcULJveA7DS3aQk0PG5RylZwtra3xibjJ6uRJjgBkXwgCSNJLVnqphFZFE5Xznt95x2KY/1kCTv5Bbl7vxj+JTeKXMQ+SILutQmad/8nGYMqrxkvIB6OHJwvnfwoEp7kDr5SC37IOdT8MnVz4RcQd0bPQoR1XIsETHWUxPFC1hFkVGHGcQxjs6FnMa5YOQUyPwwUQfe9VjdTpdrEEEzgEosJXOGNiof07bODHGK2yA41fa1p1SrmebemZysV8OWEr3HKqZB0Uq23gn41VHef4ICslPWeYS+dOrG72yXGPwvRX8D+r3tOrtYXefrS2flz0zf95yLcZ/u2i80YddzDk53/zMtY1vS5SwUPVLZe/3FNpAvuPtY=
