#!/bin/bash
set -o errexit
set -o nounset
set -o pipefail

pushd $(cd `dirname "${BASH_SOURCE[0]}"` && pwd)

VERSION=v`cat package.json | jq '.version' | tr -d '"'`
git flow release finish -m "Finish release" ${VERSION}
git push origin --all
git push origin --tags

popd
